version: '2'

services:
  zeronet:
    build: ./
    read_only: false
    networks:
      - isolated
    ports:
      - 15441:15441
    volumes:
      - data:/data

volumes:
  data: {}

networks:
  isolated:
    external:
      name: isolated
